[project]
name = "agenticlangchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ashiii27", email = "ashiii.2790@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "langchain>=1.3.18",
    "langchain-community>=0.4.2",
    "langchain-google-genai>=4.3.7",
    "langchain-google-vertexai>=3.2.4",
    "langchain-groq>=1.1.3",
    "python-dotenv>=1.2.3",
]

[project.scripts]
agenticlangchain = "agenticlangchain:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
